stages:
  - build
  - deploy

packen:
  image: node:latest
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install
    - webpack --mode production
    - cd build
    #- if [ "${CI_COMMIT_TAG}" != "" ]; then TAG="-${CI_COMMIT_TAG}"; else TAG=""; fi
    #- tar -czf ${CI_PROJECT_NAME}${TAG}.tar.gz *
    #- mv ./${CI_PROJECT_NAME}${TAG}.tar.gz ..
    - cd ..
  artifacts:
    paths:
      - ./build
      #- ${CI_PROJECT_NAME}${TAG}.tar.gz
  only:
    - webpack

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    #- ssh -vvv -p 44 dditools.inf.tu-dresden.de
    # - sshpass -p ${PASS} ssh -vvv -p 44 ${USER}dditools.inf.tu-dresden.de
    #- sshpass -e sftp -vr -P 44 -o StrictHostKeyChecking=no deploy@dditools.inf.tu-dresden.de:dditools/struktog <<< $'put ./build'
    #- sshpass -e sftp -v -P 44 ${USER}@dditools.inf.tu-dresden.de:dditools <<< $'ls'
    - sshpass -e scp -o stricthostkeychecking=no -r ./build deploy@dditools.inf.tu-dresden.de:dditools/struktog
  variables:
    GIT_STRATEGY: none
  only:
    - webpack
