stages:
  - build
  - deploymaster
  - deploydev
  - ontags

packen:
  image: node:fermium
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install yarn
    - yarn
    - yarn run build
    - cd build
    - if [ "${CI_COMMIT_TAG}" != "" ]; then TAG="-${CI_COMMIT_TAG}"; else TAG="-latest"; fi
    - tar -czf ${CI_PROJECT_NAME}${TAG}.tar.gz *
    - mkdir ../release
    - mv ./${CI_PROJECT_NAME}${TAG}.tar.gz ../release/
    - cd ..
  artifacts:
    paths:
      - ./release
      - ./build
  only:
    - master
    - development
    - tags

deploy:
  image: alpine:latest
  stage: deploymaster
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    #- apk add --no-cache openssh
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- apk add --no-cache sshpass
    #- apk add --no-cache openssh
    #- export SSHPASS=${PASS}
    #- ls
    #- sshpass -e ssh -o stricthostkeychecking=no -p 44 deploy@dditools.inf.tu-dresden.de "rm -rf ./dditools/struktog/*"
    #- sshpass -e scp -o stricthostkeychecking=no -P 44 -r ./build/* deploy@dditools.inf.tu-dresden.de:dditools/struktog
    #- sshpass -e scp -o stricthostkeychecking=no -P 44 ./release/${CI_PROJECT_NAME}-latest.tar.gz deploy@dditools.inf.tu-dresden.de:dditools/releases/struktog
    - ssh -o stricthostkeychecking=no deploy@5.189.136.208 "rm -rf ./tools/struktog/*"
  variables:
    GIT_STRATEGY: none
  only:
    - master

ontags:
  image: alpine:latest
  stage: ontags
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    - sshpass -e scp -o stricthostkeychecking=no -P 44 ./release/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz deploy@dditools.inf.tu-dresden.de:dditools/releases/struktog
  only:
    - tags

deploydev:
  image: alpine:latest
  stage: deploydev
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    - sshpass -e ssh -o stricthostkeychecking=no -p 44 deploy@dditools.inf.tu-dresden.de "rm -rf ./dditools/dev/struktog/*"
    - sshpass -e scp -o stricthostkeychecking=no -P 44 -r ./build/* deploy@dditools.inf.tu-dresden.de:dditools/dev/struktog
  variables:
    GIT_STRATEGY: none
  only:
    - development
