stages:
  - build

buildGame:
  image: node:latest
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install
    - npm build
    - cd build
    - tar -czf tool.tar.gz *
    - mv ./tool.tar.gz ..
  artifacts:
    paths:
      - tool.tar.gz
  only:
    - webpack
