stages:
  - build
  - deploymaster
  - deploydev
  - ontags

packen:
  image: node:erbium
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install
    - webpack --mode production
    - cd build
    - if [ "${CI_COMMIT_TAG}" != "" ]; then TAG="-${CI_COMMIT_TAG}"; else TAG="-latest"; fi
    - tar -czf ${CI_PROJECT_NAME}${TAG}.tar.gz *
    - mkdir ../release
    - mv ./${CI_PROJECT_NAME}${TAG}.tar.gz ../release/
    - cd ..
  artifacts:
    paths:
      - ./release
      - ./build
  only:
    - master
    - development
    - tags

deploy:
  image: alpine:latest
  stage: deploymaster
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    - ls
    - sshpass -e ssh -o stricthostkeychecking=no -p 44 deploy@dditools.inf.tu-dresden.de "rm -rf ./dditools/struktog/*"
    - sshpass -e scp -o stricthostkeychecking=no -P 44 -r ./build/* deploy@dditools.inf.tu-dresden.de:dditools/struktog
    - sshpass -e scp -o stricthostkeychecking=no -P 44 ./release/${CI_PROJECT_NAME}-latest.tar.gz deploy@dditools.inf.tu-dresden.de:dditools/releases/struktog
  variables:
    GIT_STRATEGY: none
  only:
    - master

ontags:
  image: alpine:latest
  stage: ontags
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    - sshpass -e scp -o stricthostkeychecking=no -P 44 ./release/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz deploy@dditools.inf.tu-dresden.de:dditools/releases/struktog
  only:
    - tags

deploydev:
  image: alpine:latest
  stage: deploydev
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    - sshpass -e ssh -o stricthostkeychecking=no -p 44 deploy@dditools.inf.tu-dresden.de "rm -rf ./dditools/dev/struktog/*"
    - sshpass -e scp -o stricthostkeychecking=no -P 44 -r ./build/* deploy@dditools.inf.tu-dresden.de:dditools/dev/struktog
  variables:
    GIT_STRATEGY: none
  only:
    - development
