stages:
  - build
  - deploy

packen:
  image: node:latest
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install
    - webpack --mode production
    - cd build
    - if [ "${CI_COMMIT_TAG}" != "" ]; then TAG="-${CI_COMMIT_TAG}"; else TAG=""; fi
    - tar -czf ${CI_PROJECT_NAME}${TAG}.tar.gz *
    - mv ./${CI_PROJECT_NAME}${TAG}.tar.gz ..
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}${TAG}.tar.gz
  only:
    - webpack

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache sshpass
    - apk add --no-cache openssh
    - export SSHPASS=${PASS}
    #- sftp -v -P 44 deploy@dditools.inf.tu-dresden.de
    #- exit
    - sshpass -e sftp -v -P 44 ${USER}@dditools.inf.tu-dresden.de:dditools <<< $'ls'
  variables:
    GIT_STRATEGY: none
  only:
    - webpack
