stages:
  - build

buildGame:
  image: node:latest
  stage: build
  script:
    - PATH="./node_modules/.bin:$PATH"
    - npm install
    - npm build
    - cd build
    - tar -czf tool.tar.gz *
    - mv ./tool.tar.gz ..
  artifacts:
    paths:
      - tool.tar.gz

deployGame:
  image: alpine:latest
  stage: deploy
  script:
    - apk add --no-cache curl
    - curl -v --data-binary @game.tar.gz ${DEPLOY_URL}/${CI_PROJECT_NAME}?token=${DEPLOY_TOKEN} | cat
  variables:
    GIT_STRATEGY: none
  only:
    - webpack
